// <auto-generated />
using System;
using MiMochiRentals.DBContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MiMochiRentals.Migrations
{
    [DbContext(typeof(MMContext))]
    [Migration("20251217160321_seedItems_N_Orders")]
    partial class seedItems_N_Orders
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.22");

            modelBuilder.Entity("MiMochiRentals.Models.Item", b =>
                {
                    b.Property<int>("itemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ItemTypeCode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("bond")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("endDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("endPeriod")
                        .HasColumnType("INTEGER");

                    b.Property<int>("orderID")
                        .HasColumnType("INTEGER");

                    b.Property<int>("price")
                        .HasColumnType("INTEGER");

                    b.Property<int>("quantity")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("startDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("startPeriod")
                        .HasMaxLength(3)
                        .HasColumnType("INTEGER");

                    b.HasKey("itemId");

                    b.HasIndex("ItemTypeCode");

                    b.HasIndex("itemId")
                        .IsUnique();

                    b.HasIndex("orderID");

                    b.ToTable("Items");

                    b.HasData(
                        new
                        {
                            itemId = 1,
                            ItemTypeCode = "w-set-001",
                            bond = 100,
                            endDate = new DateTime(2025, 5, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            endPeriod = 2,
                            orderID = 1,
                            price = 900,
                            quantity = 1,
                            startDate = new DateTime(2025, 5, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            startPeriod = 1
                        },
                        new
                        {
                            itemId = 2,
                            ItemTypeCode = "w-chair-001",
                            bond = 50,
                            endDate = new DateTime(2025, 5, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            endPeriod = 2,
                            orderID = 1,
                            price = 3,
                            quantity = 50,
                            startDate = new DateTime(2025, 5, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            startPeriod = 1
                        },
                        new
                        {
                            itemId = 3,
                            ItemTypeCode = "blu-cb-001",
                            bond = 50,
                            endDate = new DateTime(2025, 6, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            endPeriod = 2,
                            orderID = 2,
                            price = 50,
                            quantity = 1,
                            startDate = new DateTime(2025, 6, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            startPeriod = 2
                        },
                        new
                        {
                            itemId = 4,
                            ItemTypeCode = "blu-dt-001",
                            bond = 100,
                            endDate = new DateTime(2025, 6, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            endPeriod = 2,
                            orderID = 2,
                            price = 100,
                            quantity = 1,
                            startDate = new DateTime(2025, 6, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            startPeriod = 2
                        },
                        new
                        {
                            itemId = 5,
                            ItemTypeCode = "w-tent-001",
                            bond = 100,
                            endDate = new DateTime(2025, 7, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            endPeriod = 1,
                            orderID = 3,
                            price = 60,
                            quantity = 2,
                            startDate = new DateTime(2025, 7, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            startPeriod = 1
                        },
                        new
                        {
                            itemId = 6,
                            ItemTypeCode = "w-floralArch-001",
                            bond = 100,
                            endDate = new DateTime(2025, 7, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            endPeriod = 1,
                            orderID = 3,
                            price = 160,
                            quantity = 1,
                            startDate = new DateTime(2025, 7, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            startPeriod = 1
                        },
                        new
                        {
                            itemId = 7,
                            ItemTypeCode = "mc-cb-001",
                            bond = 50,
                            endDate = new DateTime(2025, 8, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            endPeriod = 3,
                            orderID = 4,
                            price = 50,
                            quantity = 1,
                            startDate = new DateTime(2025, 8, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            startPeriod = 1
                        },
                        new
                        {
                            itemId = 8,
                            ItemTypeCode = "mc-dt-001",
                            bond = 1,
                            endDate = new DateTime(2025, 8, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            endPeriod = 3,
                            orderID = 4,
                            price = 1,
                            quantity = 1,
                            startDate = new DateTime(2025, 8, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            startPeriod = 1
                        },
                        new
                        {
                            itemId = 9,
                            ItemTypeCode = "mlp-ra-003",
                            bond = 100,
                            endDate = new DateTime(2025, 9, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            endPeriod = 2,
                            orderID = 5,
                            price = 120,
                            quantity = 1,
                            startDate = new DateTime(2025, 9, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            startPeriod = 1
                        },
                        new
                        {
                            itemId = 10,
                            ItemTypeCode = "mlp-tb-001",
                            bond = 50,
                            endDate = new DateTime(2025, 9, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            endPeriod = 2,
                            orderID = 5,
                            price = 60,
                            quantity = 1,
                            startDate = new DateTime(2025, 9, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            startPeriod = 1
                        });
                });

            modelBuilder.Entity("MiMochiRentals.Models.ItemType", b =>
                {
                    b.Property<string>("code")
                        .HasColumnType("TEXT");

                    b.Property<int>("bond")
                        .HasColumnType("INTEGER");

                    b.Property<string>("genre")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("isSet")
                        .HasColumnType("INTEGER");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("price")
                        .HasColumnType("INTEGER");

                    b.Property<double>("sHeight")
                        .HasColumnType("REAL");

                    b.Property<double>("sLength")
                        .HasColumnType("REAL");

                    b.Property<double>("sWidth")
                        .HasColumnType("REAL");

                    b.Property<int>("totalQuantity")
                        .HasColumnType("INTEGER");

                    b.Property<string>("type")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("weight")
                        .HasColumnType("REAL");

                    b.HasKey("code");

                    b.HasIndex("code")
                        .IsUnique();

                    b.ToTable("Types");

                    b.HasData(
                        new
                        {
                            code = "bbs-cb-001",
                            bond = 50,
                            genre = "birthday",
                            isSet = false,
                            name = "baby-shark",
                            price = 50,
                            sHeight = 1.0,
                            sLength = 1.0,
                            sWidth = 1.0,
                            totalQuantity = 1,
                            type = "circle-board",
                            weight = 0.0
                        },
                        new
                        {
                            code = "bbs-dt-001",
                            bond = 1,
                            genre = "birthday",
                            isSet = false,
                            name = "baby-shark",
                            price = 1,
                            sHeight = 1.0,
                            sLength = 1.0,
                            sWidth = 1.0,
                            totalQuantity = 1,
                            type = "dessert-table",
                            weight = 0.0
                        },
                        new
                        {
                            code = "mc-cb-001",
                            bond = 50,
                            genre = "birthday",
                            isSet = false,
                            name = "minecraft",
                            price = 50,
                            sHeight = 1.0,
                            sLength = 1.0,
                            sWidth = 1.0,
                            totalQuantity = 1,
                            type = "circle-board",
                            weight = 0.0
                        },
                        new
                        {
                            code = "mc-dt-001",
                            bond = 1,
                            genre = "birthday",
                            isSet = false,
                            name = "minecraft",
                            price = 1,
                            sHeight = 1.0,
                            sLength = 1.0,
                            sWidth = 1.0,
                            totalQuantity = 1,
                            type = "dessert-table",
                            weight = 0.0
                        },
                        new
                        {
                            code = "cm-cb-001",
                            bond = 50,
                            genre = "birthday",
                            isSet = false,
                            name = "cocomelon",
                            price = 50,
                            sHeight = 1.0,
                            sLength = 1.0,
                            sWidth = 1.0,
                            totalQuantity = 1,
                            type = "circle-board",
                            weight = 0.0
                        },
                        new
                        {
                            code = "cm-dt-001",
                            bond = 1,
                            genre = "birthday",
                            isSet = false,
                            name = "cocomelon",
                            price = 1,
                            sHeight = 1.0,
                            sLength = 1.0,
                            sWidth = 1.0,
                            totalQuantity = 1,
                            type = "dessert-table",
                            weight = 0.0
                        },
                        new
                        {
                            code = "cm-tb-001",
                            bond = 50,
                            genre = "birthday",
                            isSet = false,
                            name = "cocomelon",
                            price = 60,
                            sHeight = 1.0,
                            sLength = 1.0,
                            sWidth = 1.0,
                            totalQuantity = 1,
                            type = "theme-board",
                            weight = 0.0
                        },
                        new
                        {
                            code = "cm-tb-002",
                            bond = 50,
                            genre = "birthday",
                            isSet = false,
                            name = "cocomelon",
                            price = 50,
                            sHeight = 1.0,
                            sLength = 1.0,
                            sWidth = 1.0,
                            totalQuantity = 1,
                            type = "theme-board",
                            weight = 0.0
                        },
                        new
                        {
                            code = "cm-tb-003",
                            bond = 50,
                            genre = "birthday",
                            isSet = false,
                            name = "cocomelon",
                            price = 50,
                            sHeight = 1.0,
                            sLength = 1.0,
                            sWidth = 1.0,
                            totalQuantity = 1,
                            type = "theme-board",
                            weight = 0.0
                        },
                        new
                        {
                            code = "blu-cb-001",
                            bond = 50,
                            genre = "birthday",
                            isSet = false,
                            name = "bluey",
                            price = 50,
                            sHeight = 1.0,
                            sLength = 1.0,
                            sWidth = 1.0,
                            totalQuantity = 1,
                            type = "circle-board",
                            weight = 0.0
                        },
                        new
                        {
                            code = "blu-dt-001",
                            bond = 100,
                            genre = "birthday",
                            isSet = false,
                            name = "bluey",
                            price = 100,
                            sHeight = 1.0,
                            sLength = 1.0,
                            sWidth = 1.0,
                            totalQuantity = 1,
                            type = "dessert-table",
                            weight = 0.0
                        },
                        new
                        {
                            code = "pep-cb-001",
                            bond = 50,
                            genre = "birthday",
                            isSet = false,
                            name = "peppa-pig",
                            price = 50,
                            sHeight = 1.0,
                            sLength = 1.0,
                            sWidth = 1.0,
                            totalQuantity = 1,
                            type = "circle-board",
                            weight = 0.0
                        },
                        new
                        {
                            code = "pep-dt-001",
                            bond = 1,
                            genre = "birthday",
                            isSet = false,
                            name = "peppa-pig",
                            price = 1,
                            sHeight = 1.0,
                            sLength = 1.0,
                            sWidth = 1.0,
                            totalQuantity = 1,
                            type = "dessert-table",
                            weight = 0.0
                        },
                        new
                        {
                            code = "pep-tb-001",
                            bond = 50,
                            genre = "birthday",
                            isSet = false,
                            name = "peppa-pig",
                            price = 60,
                            sHeight = 1.0,
                            sLength = 1.0,
                            sWidth = 1.0,
                            totalQuantity = 1,
                            type = "theme-board",
                            weight = 0.0
                        },
                        new
                        {
                            code = "pep-tb-002",
                            bond = 50,
                            genre = "birthday",
                            isSet = false,
                            name = "peppa-pig",
                            price = 50,
                            sHeight = 1.0,
                            sLength = 1.0,
                            sWidth = 1.0,
                            totalQuantity = 1,
                            type = "theme-board",
                            weight = 0.0
                        },
                        new
                        {
                            code = "pep-tb-003",
                            bond = 50,
                            genre = "birthday",
                            isSet = false,
                            name = "peppa-pig",
                            price = 50,
                            sHeight = 1.0,
                            sLength = 1.0,
                            sWidth = 1.0,
                            totalQuantity = 1,
                            type = "theme-board",
                            weight = 0.0
                        },
                        new
                        {
                            code = "spi-cb-001",
                            bond = 50,
                            genre = "birthday",
                            isSet = false,
                            name = "spidey",
                            price = 50,
                            sHeight = 1.0,
                            sLength = 1.0,
                            sWidth = 1.0,
                            totalQuantity = 1,
                            type = "circle-board",
                            weight = 0.0
                        },
                        new
                        {
                            code = "spi-dt-001",
                            bond = 1,
                            genre = "birthday",
                            isSet = false,
                            name = "spi",
                            price = 1,
                            sHeight = 1.0,
                            sLength = 1.0,
                            sWidth = 1.0,
                            totalQuantity = 1,
                            type = "dessert-table",
                            weight = 0.0
                        },
                        new
                        {
                            code = "mlp-tb-001",
                            bond = 50,
                            genre = "birthday",
                            isSet = false,
                            name = "my-little-pony",
                            price = 60,
                            sHeight = 1.0,
                            sLength = 1.0,
                            sWidth = 1.0,
                            totalQuantity = 1,
                            type = "theme-board",
                            weight = 0.0
                        },
                        new
                        {
                            code = "mlp-tb-002",
                            bond = 50,
                            genre = "birthday",
                            isSet = false,
                            name = "my-little-pony",
                            price = 50,
                            sHeight = 1.0,
                            sLength = 1.0,
                            sWidth = 1.0,
                            totalQuantity = 1,
                            type = "theme-board",
                            weight = 0.0
                        },
                        new
                        {
                            code = "mlp-tb-003",
                            bond = 100,
                            genre = "birthday",
                            isSet = false,
                            name = "my-little-pony",
                            price = 100,
                            sHeight = 1.0,
                            sLength = 1.0,
                            sWidth = 1.0,
                            totalQuantity = 1,
                            type = "theme-board",
                            weight = 0.0
                        },
                        new
                        {
                            code = "mlp-ra-001",
                            bond = 100,
                            genre = "birthday",
                            isSet = false,
                            name = "my-little-pony",
                            price = 60,
                            sHeight = 1.0,
                            sLength = 1.0,
                            sWidth = 1.0,
                            totalQuantity = 1,
                            type = "rainbow-arc",
                            weight = 0.0
                        },
                        new
                        {
                            code = "mlp-ra-002",
                            bond = 100,
                            genre = "birthday",
                            isSet = false,
                            name = "my-little-pony",
                            price = 60,
                            sHeight = 1.0,
                            sLength = 1.0,
                            sWidth = 1.0,
                            totalQuantity = 1,
                            type = "rainbow-arc",
                            weight = 0.0
                        },
                        new
                        {
                            code = "mlp-ra-003",
                            bond = 100,
                            genre = "birthday",
                            isSet = false,
                            name = "my-little-pony",
                            price = 120,
                            sHeight = 1.0,
                            sLength = 1.0,
                            sWidth = 1.0,
                            totalQuantity = 1,
                            type = "rainbow-arc",
                            weight = 0.0
                        },
                        new
                        {
                            code = "frz-tb-001",
                            bond = 50,
                            genre = "birthday",
                            isSet = false,
                            name = "frozen",
                            price = 60,
                            sHeight = 1.0,
                            sLength = 1.0,
                            sWidth = 1.0,
                            totalQuantity = 1,
                            type = "theme-board",
                            weight = 0.0
                        },
                        new
                        {
                            code = "frz-tb-002",
                            bond = 50,
                            genre = "birthday",
                            isSet = false,
                            name = "frozen",
                            price = 50,
                            sHeight = 1.0,
                            sLength = 1.0,
                            sWidth = 1.0,
                            totalQuantity = 1,
                            type = "theme-board",
                            weight = 0.0
                        },
                        new
                        {
                            code = "frz-tb-003",
                            bond = 50,
                            genre = "birthday",
                            isSet = false,
                            name = "frozen",
                            price = 50,
                            sHeight = 1.0,
                            sLength = 1.0,
                            sWidth = 1.0,
                            totalQuantity = 1,
                            type = "theme-board",
                            weight = 0.0
                        },
                        new
                        {
                            code = "w-table-blue-001",
                            bond = 50,
                            genre = "wedding",
                            isSet = false,
                            name = "table-blue",
                            price = 10,
                            sHeight = 1.0,
                            sLength = 1.0,
                            sWidth = 1.0,
                            totalQuantity = 2,
                            type = "table",
                            weight = 0.0
                        },
                        new
                        {
                            code = "w-table-white-001",
                            bond = 50,
                            genre = "wedding",
                            isSet = false,
                            name = "table-white",
                            price = 10,
                            sHeight = 1.0,
                            sLength = 1.0,
                            sWidth = 1.0,
                            totalQuantity = 2,
                            type = "table",
                            weight = 0.0
                        },
                        new
                        {
                            code = "w-chair-001",
                            bond = 100,
                            genre = "wedding",
                            isSet = false,
                            name = "chair",
                            price = 3,
                            sHeight = 1.0,
                            sLength = 1.0,
                            sWidth = 1.0,
                            totalQuantity = 100,
                            type = "chair",
                            weight = 0.0
                        },
                        new
                        {
                            code = "w-tent-001",
                            bond = 100,
                            genre = "wedding",
                            isSet = false,
                            name = "tent",
                            price = 60,
                            sHeight = 1.0,
                            sLength = 1.0,
                            sWidth = 1.0,
                            totalQuantity = 3,
                            type = "tent",
                            weight = 0.0
                        },
                        new
                        {
                            code = "w-chaffing-001",
                            bond = 100,
                            genre = "wedding",
                            isSet = false,
                            name = "chaffing-dish",
                            price = 10,
                            sHeight = 1.0,
                            sLength = 1.0,
                            sWidth = 1.0,
                            totalQuantity = 10,
                            type = "chaffing dish",
                            weight = 0.0
                        },
                        new
                        {
                            code = "w-set-001",
                            bond = 100,
                            genre = "wedding",
                            isSet = true,
                            name = "wedding-fullset",
                            price = 900,
                            sHeight = 1.0,
                            sLength = 1.0,
                            sWidth = 1.0,
                            totalQuantity = 1,
                            type = "fullset",
                            weight = 0.0
                        },
                        new
                        {
                            code = "w-dessert-001",
                            bond = 100,
                            genre = "wedding",
                            isSet = false,
                            name = "dessert-table",
                            price = 100,
                            sHeight = 1.0,
                            sLength = 1.0,
                            sWidth = 1.0,
                            totalQuantity = 1,
                            type = "dessert-table",
                            weight = 0.0
                        },
                        new
                        {
                            code = "w-floralArch-001",
                            bond = 100,
                            genre = "wedding",
                            isSet = false,
                            name = "floral-arch",
                            price = 160,
                            sHeight = 1.0,
                            sLength = 1.0,
                            sWidth = 1.0,
                            totalQuantity = 1,
                            type = "floral-arch",
                            weight = 0.0
                        },
                        new
                        {
                            code = "w-background-001",
                            bond = 100,
                            genre = "wedding",
                            isSet = false,
                            name = "floral-background",
                            price = 120,
                            sHeight = 1.0,
                            sLength = 1.0,
                            sWidth = 1.0,
                            totalQuantity = 2,
                            type = "floral-background",
                            weight = 0.0
                        },
                        new
                        {
                            code = "w-woodenArch-001",
                            bond = 100,
                            genre = "wedding",
                            isSet = false,
                            name = "wooden-arch",
                            price = 100,
                            sHeight = 1.0,
                            sLength = 1.0,
                            sWidth = 1.0,
                            totalQuantity = 1,
                            type = "wooden-arch",
                            weight = 0.0
                        },
                        new
                        {
                            code = "w-steelArch-001",
                            bond = 100,
                            genre = "wedding",
                            isSet = false,
                            name = "steel-arch",
                            price = 70,
                            sHeight = 1.0,
                            sLength = 1.0,
                            sWidth = 1.0,
                            totalQuantity = 3,
                            type = "steel-arch",
                            weight = 0.0
                        },
                        new
                        {
                            code = "w-carpet-001",
                            bond = 100,
                            genre = "wedding",
                            isSet = false,
                            name = "carpet",
                            price = 80,
                            sHeight = 1.0,
                            sLength = 1.0,
                            sWidth = 1.0,
                            totalQuantity = 1,
                            type = "carpet",
                            weight = 0.0
                        });
                });

            modelBuilder.Entity("MiMochiRentals.Models.Order", b =>
                {
                    b.Property<int>("orderID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("bond")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("bondReturned")
                        .HasColumnType("INTEGER");

                    b.Property<int>("customerID")
                        .HasColumnType("INTEGER");

                    b.Property<int>("orderVal")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("paid")
                        .HasColumnType("INTEGER");

                    b.Property<int>("receiptNo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.HasKey("orderID");

                    b.HasIndex("receiptNo")
                        .IsUnique();

                    b.ToTable("Orders");

                    b.HasData(
                        new
                        {
                            orderID = 1,
                            bond = 5000,
                            bondReturned = false,
                            customerID = 1,
                            orderVal = 15000,
                            paid = true,
                            receiptNo = 1
                        },
                        new
                        {
                            orderID = 2,
                            bond = 3000,
                            bondReturned = true,
                            customerID = 1,
                            orderVal = 8500,
                            paid = true,
                            receiptNo = 2
                        },
                        new
                        {
                            orderID = 3,
                            bond = 7500,
                            bondReturned = false,
                            customerID = 3,
                            orderVal = 22000,
                            paid = false,
                            receiptNo = 3
                        },
                        new
                        {
                            orderID = 4,
                            bond = 4000,
                            bondReturned = true,
                            customerID = 2,
                            orderVal = 12000,
                            paid = true,
                            receiptNo = 4
                        },
                        new
                        {
                            orderID = 5,
                            bond = 6000,
                            bondReturned = false,
                            customerID = 3,
                            orderVal = 18500,
                            paid = true,
                            receiptNo = 5
                        });
                });

            modelBuilder.Entity("MiMochiRentals.Models.Item", b =>
                {
                    b.HasOne("MiMochiRentals.Models.ItemType", null)
                        .WithMany()
                        .HasForeignKey("ItemTypeCode")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MiMochiRentals.Models.Order", null)
                        .WithMany("items")
                        .HasForeignKey("orderID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MiMochiRentals.Models.Order", b =>
                {
                    b.Navigation("items");
                });
#pragma warning restore 612, 618
        }
    }
}
