// <auto-generated />
using System;
using MiMochiRentals.DBContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MiMochiRentals.Migrations
{
    [DbContext(typeof(MMContext))]
    [Migration("20251205034058_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.22");

            modelBuilder.Entity("MiMochiRentals.Models.Item", b =>
                {
                    b.Property<int>("itemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ItemTypeCode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("bond")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("endDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("orderID")
                        .HasColumnType("TEXT");

                    b.Property<int>("price")
                        .HasColumnType("INTEGER");

                    b.Property<int>("quantity")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("startDate")
                        .HasColumnType("TEXT");

                    b.HasKey("itemId");

                    b.HasIndex("itemId")
                        .IsUnique();

                    b.HasIndex("orderID");

                    b.ToTable("Items");
                });

            modelBuilder.Entity("MiMochiRentals.Models.ItemType", b =>
                {
                    b.Property<string>("code")
                        .HasColumnType("TEXT");

                    b.Property<int>("bond")
                        .HasColumnType("INTEGER");

                    b.Property<string>("genre")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("isSet")
                        .HasColumnType("INTEGER");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("price")
                        .HasColumnType("INTEGER");

                    b.Property<double>("sHeight")
                        .HasColumnType("REAL");

                    b.Property<double>("sLength")
                        .HasColumnType("REAL");

                    b.Property<double>("sWidth")
                        .HasColumnType("REAL");

                    b.Property<int>("totalQuantity")
                        .HasColumnType("INTEGER");

                    b.Property<string>("type")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("weight")
                        .HasColumnType("REAL");

                    b.HasKey("code");

                    b.HasIndex("code")
                        .IsUnique();

                    b.ToTable("Types");

                    b.HasData(
                        new
                        {
                            code = "bbs-cb-001",
                            bond = 50,
                            genre = "birthday",
                            isSet = false,
                            name = "baby-shark",
                            price = 50,
                            sHeight = 1.0,
                            sLength = 1.0,
                            sWidth = 1.0,
                            totalQuantity = 1,
                            type = "circle-board",
                            weight = 0.0
                        },
                        new
                        {
                            code = "bbs-dt-001",
                            bond = 1,
                            genre = "birthday",
                            isSet = false,
                            name = "baby-shark",
                            price = 1,
                            sHeight = 1.0,
                            sLength = 1.0,
                            sWidth = 1.0,
                            totalQuantity = 1,
                            type = "dessert-table",
                            weight = 0.0
                        },
                        new
                        {
                            code = "mc-cb-001",
                            bond = 50,
                            genre = "birthday",
                            isSet = false,
                            name = "minecraft",
                            price = 50,
                            sHeight = 1.0,
                            sLength = 1.0,
                            sWidth = 1.0,
                            totalQuantity = 1,
                            type = "circle-board",
                            weight = 0.0
                        },
                        new
                        {
                            code = "mc-dt-001",
                            bond = 1,
                            genre = "birthday",
                            isSet = false,
                            name = "minecraft",
                            price = 1,
                            sHeight = 1.0,
                            sLength = 1.0,
                            sWidth = 1.0,
                            totalQuantity = 1,
                            type = "dessert-table",
                            weight = 0.0
                        },
                        new
                        {
                            code = "cm-cb-001",
                            bond = 50,
                            genre = "birthday",
                            isSet = false,
                            name = "cocomelon",
                            price = 50,
                            sHeight = 1.0,
                            sLength = 1.0,
                            sWidth = 1.0,
                            totalQuantity = 1,
                            type = "circle-board",
                            weight = 0.0
                        },
                        new
                        {
                            code = "cm-dt-001",
                            bond = 1,
                            genre = "birthday",
                            isSet = false,
                            name = "cocomelon",
                            price = 1,
                            sHeight = 1.0,
                            sLength = 1.0,
                            sWidth = 1.0,
                            totalQuantity = 1,
                            type = "dessert-table",
                            weight = 0.0
                        },
                        new
                        {
                            code = "cm-tb-001",
                            bond = 50,
                            genre = "birthday",
                            isSet = false,
                            name = "cocomelon",
                            price = 60,
                            sHeight = 1.0,
                            sLength = 1.0,
                            sWidth = 1.0,
                            totalQuantity = 1,
                            type = "theme-board",
                            weight = 0.0
                        },
                        new
                        {
                            code = "cm-tb-002",
                            bond = 50,
                            genre = "birthday",
                            isSet = false,
                            name = "cocomelon",
                            price = 50,
                            sHeight = 1.0,
                            sLength = 1.0,
                            sWidth = 1.0,
                            totalQuantity = 1,
                            type = "theme-board",
                            weight = 0.0
                        },
                        new
                        {
                            code = "cm-tb-003",
                            bond = 50,
                            genre = "birthday",
                            isSet = false,
                            name = "cocomelon",
                            price = 50,
                            sHeight = 1.0,
                            sLength = 1.0,
                            sWidth = 1.0,
                            totalQuantity = 1,
                            type = "theme-board",
                            weight = 0.0
                        },
                        new
                        {
                            code = "blu-cb-001",
                            bond = 50,
                            genre = "birthday",
                            isSet = false,
                            name = "bluey",
                            price = 50,
                            sHeight = 1.0,
                            sLength = 1.0,
                            sWidth = 1.0,
                            totalQuantity = 1,
                            type = "circle-board",
                            weight = 0.0
                        },
                        new
                        {
                            code = "blu-dt-001",
                            bond = 100,
                            genre = "birthday",
                            isSet = false,
                            name = "bluey",
                            price = 100,
                            sHeight = 1.0,
                            sLength = 1.0,
                            sWidth = 1.0,
                            totalQuantity = 1,
                            type = "dessert-table",
                            weight = 0.0
                        },
                        new
                        {
                            code = "pep-cb-001",
                            bond = 50,
                            genre = "birthday",
                            isSet = false,
                            name = "peppa-pig",
                            price = 50,
                            sHeight = 1.0,
                            sLength = 1.0,
                            sWidth = 1.0,
                            totalQuantity = 1,
                            type = "circle-board",
                            weight = 0.0
                        },
                        new
                        {
                            code = "pep-dt-001",
                            bond = 1,
                            genre = "birthday",
                            isSet = false,
                            name = "peppa-pig",
                            price = 1,
                            sHeight = 1.0,
                            sLength = 1.0,
                            sWidth = 1.0,
                            totalQuantity = 1,
                            type = "dessert-table",
                            weight = 0.0
                        },
                        new
                        {
                            code = "pep-tb-001",
                            bond = 50,
                            genre = "birthday",
                            isSet = false,
                            name = "peppa-pig",
                            price = 60,
                            sHeight = 1.0,
                            sLength = 1.0,
                            sWidth = 1.0,
                            totalQuantity = 1,
                            type = "theme-board",
                            weight = 0.0
                        },
                        new
                        {
                            code = "pep-tb-002",
                            bond = 50,
                            genre = "birthday",
                            isSet = false,
                            name = "peppa-pig",
                            price = 50,
                            sHeight = 1.0,
                            sLength = 1.0,
                            sWidth = 1.0,
                            totalQuantity = 1,
                            type = "theme-board",
                            weight = 0.0
                        },
                        new
                        {
                            code = "pep-tb-003",
                            bond = 50,
                            genre = "birthday",
                            isSet = false,
                            name = "peppa-pig",
                            price = 50,
                            sHeight = 1.0,
                            sLength = 1.0,
                            sWidth = 1.0,
                            totalQuantity = 1,
                            type = "theme-board",
                            weight = 0.0
                        },
                        new
                        {
                            code = "spi-cb-001",
                            bond = 50,
                            genre = "birthday",
                            isSet = false,
                            name = "spidey",
                            price = 50,
                            sHeight = 1.0,
                            sLength = 1.0,
                            sWidth = 1.0,
                            totalQuantity = 1,
                            type = "circle-board",
                            weight = 0.0
                        },
                        new
                        {
                            code = "spi-dt-001",
                            bond = 1,
                            genre = "birthday",
                            isSet = false,
                            name = "spi",
                            price = 1,
                            sHeight = 1.0,
                            sLength = 1.0,
                            sWidth = 1.0,
                            totalQuantity = 1,
                            type = "dessert-table",
                            weight = 0.0
                        },
                        new
                        {
                            code = "mlp-tb-001",
                            bond = 50,
                            genre = "birthday",
                            isSet = false,
                            name = "my-little-pony",
                            price = 60,
                            sHeight = 1.0,
                            sLength = 1.0,
                            sWidth = 1.0,
                            totalQuantity = 1,
                            type = "theme-board",
                            weight = 0.0
                        },
                        new
                        {
                            code = "mlp-tb-002",
                            bond = 50,
                            genre = "birthday",
                            isSet = false,
                            name = "my-little-pony",
                            price = 50,
                            sHeight = 1.0,
                            sLength = 1.0,
                            sWidth = 1.0,
                            totalQuantity = 1,
                            type = "theme-board",
                            weight = 0.0
                        },
                        new
                        {
                            code = "mlp-tb-003",
                            bond = 100,
                            genre = "birthday",
                            isSet = false,
                            name = "my-little-pony",
                            price = 100,
                            sHeight = 1.0,
                            sLength = 1.0,
                            sWidth = 1.0,
                            totalQuantity = 1,
                            type = "theme-board",
                            weight = 0.0
                        },
                        new
                        {
                            code = "mlp-ra-001",
                            bond = 100,
                            genre = "birthday",
                            isSet = false,
                            name = "my-little-pony",
                            price = 60,
                            sHeight = 1.0,
                            sLength = 1.0,
                            sWidth = 1.0,
                            totalQuantity = 1,
                            type = "rainbow-arc",
                            weight = 0.0
                        },
                        new
                        {
                            code = "mlp-ra-002",
                            bond = 100,
                            genre = "birthday",
                            isSet = false,
                            name = "my-little-pony",
                            price = 60,
                            sHeight = 1.0,
                            sLength = 1.0,
                            sWidth = 1.0,
                            totalQuantity = 1,
                            type = "rainbow-arc",
                            weight = 0.0
                        },
                        new
                        {
                            code = "mlp-ra-003",
                            bond = 100,
                            genre = "birthday",
                            isSet = false,
                            name = "my-little-pony",
                            price = 120,
                            sHeight = 1.0,
                            sLength = 1.0,
                            sWidth = 1.0,
                            totalQuantity = 1,
                            type = "rainbow-arc",
                            weight = 0.0
                        },
                        new
                        {
                            code = "frz-tb-001",
                            bond = 50,
                            genre = "birthday",
                            isSet = false,
                            name = "frozen",
                            price = 60,
                            sHeight = 1.0,
                            sLength = 1.0,
                            sWidth = 1.0,
                            totalQuantity = 1,
                            type = "theme-board",
                            weight = 0.0
                        },
                        new
                        {
                            code = "frz-tb-002",
                            bond = 50,
                            genre = "birthday",
                            isSet = false,
                            name = "frozen",
                            price = 50,
                            sHeight = 1.0,
                            sLength = 1.0,
                            sWidth = 1.0,
                            totalQuantity = 1,
                            type = "theme-board",
                            weight = 0.0
                        },
                        new
                        {
                            code = "frz-tb-003",
                            bond = 50,
                            genre = "birthday",
                            isSet = false,
                            name = "frozen",
                            price = 50,
                            sHeight = 1.0,
                            sLength = 1.0,
                            sWidth = 1.0,
                            totalQuantity = 1,
                            type = "theme-board",
                            weight = 0.0
                        },
                        new
                        {
                            code = "w-table-blue-001",
                            bond = 50,
                            genre = "wedding",
                            isSet = false,
                            name = "table-blue",
                            price = 10,
                            sHeight = 1.0,
                            sLength = 1.0,
                            sWidth = 1.0,
                            totalQuantity = 2,
                            type = "table",
                            weight = 0.0
                        },
                        new
                        {
                            code = "w-table-white-001",
                            bond = 50,
                            genre = "wedding",
                            isSet = false,
                            name = "table-white",
                            price = 10,
                            sHeight = 1.0,
                            sLength = 1.0,
                            sWidth = 1.0,
                            totalQuantity = 2,
                            type = "table",
                            weight = 0.0
                        },
                        new
                        {
                            code = "w-chair-001",
                            bond = 100,
                            genre = "wedding",
                            isSet = false,
                            name = "chair",
                            price = 3,
                            sHeight = 1.0,
                            sLength = 1.0,
                            sWidth = 1.0,
                            totalQuantity = 100,
                            type = "chair",
                            weight = 0.0
                        },
                        new
                        {
                            code = "w-tent-001",
                            bond = 100,
                            genre = "wedding",
                            isSet = false,
                            name = "tent",
                            price = 60,
                            sHeight = 1.0,
                            sLength = 1.0,
                            sWidth = 1.0,
                            totalQuantity = 3,
                            type = "tent",
                            weight = 0.0
                        },
                        new
                        {
                            code = "w-chaffing-001",
                            bond = 100,
                            genre = "wedding",
                            isSet = false,
                            name = "chaffing-dish",
                            price = 10,
                            sHeight = 1.0,
                            sLength = 1.0,
                            sWidth = 1.0,
                            totalQuantity = 10,
                            type = "chaffing dish",
                            weight = 0.0
                        },
                        new
                        {
                            code = "w-set-001",
                            bond = 100,
                            genre = "wedding",
                            isSet = true,
                            name = "wedding-fullset",
                            price = 900,
                            sHeight = 1.0,
                            sLength = 1.0,
                            sWidth = 1.0,
                            totalQuantity = 1,
                            type = "fullset",
                            weight = 0.0
                        },
                        new
                        {
                            code = "w-dessert-001",
                            bond = 100,
                            genre = "wedding",
                            isSet = false,
                            name = "dessert-table",
                            price = 100,
                            sHeight = 1.0,
                            sLength = 1.0,
                            sWidth = 1.0,
                            totalQuantity = 1,
                            type = "dessert-table",
                            weight = 0.0
                        },
                        new
                        {
                            code = "w-floralArch-001",
                            bond = 100,
                            genre = "wedding",
                            isSet = false,
                            name = "floral-arch",
                            price = 160,
                            sHeight = 1.0,
                            sLength = 1.0,
                            sWidth = 1.0,
                            totalQuantity = 1,
                            type = "floral-arch",
                            weight = 0.0
                        },
                        new
                        {
                            code = "w-background-001",
                            bond = 100,
                            genre = "wedding",
                            isSet = false,
                            name = "floral-background",
                            price = 120,
                            sHeight = 1.0,
                            sLength = 1.0,
                            sWidth = 1.0,
                            totalQuantity = 2,
                            type = "floral-background",
                            weight = 0.0
                        },
                        new
                        {
                            code = "w-woodenArch-001",
                            bond = 100,
                            genre = "wedding",
                            isSet = false,
                            name = "wooden-arch",
                            price = 100,
                            sHeight = 1.0,
                            sLength = 1.0,
                            sWidth = 1.0,
                            totalQuantity = 1,
                            type = "wooden-arch",
                            weight = 0.0
                        },
                        new
                        {
                            code = "w-steelArch-001",
                            bond = 100,
                            genre = "wedding",
                            isSet = false,
                            name = "steel-arch",
                            price = 70,
                            sHeight = 1.0,
                            sLength = 1.0,
                            sWidth = 1.0,
                            totalQuantity = 3,
                            type = "steel-arch",
                            weight = 0.0
                        },
                        new
                        {
                            code = "w-carpet-001",
                            bond = 100,
                            genre = "wedding",
                            isSet = false,
                            name = "carpet",
                            price = 80,
                            sHeight = 1.0,
                            sLength = 1.0,
                            sWidth = 1.0,
                            totalQuantity = 1,
                            type = "carpet",
                            weight = 0.0
                        });
                });

            modelBuilder.Entity("MiMochiRentals.Models.Order", b =>
                {
                    b.Property<string>("orderID")
                        .HasColumnType("TEXT");

                    b.Property<int>("bond")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("bondReturned")
                        .HasColumnType("INTEGER");

                    b.Property<string>("customerID")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("orderVal")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("paid")
                        .HasColumnType("INTEGER");

                    b.Property<string>("receiptNo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("orderID");

                    b.HasIndex("receiptNo")
                        .IsUnique();

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("MiMochiRentals.Models.Item", b =>
                {
                    b.HasOne("MiMochiRentals.Models.Order", null)
                        .WithMany("items")
                        .HasForeignKey("orderID");
                });

            modelBuilder.Entity("MiMochiRentals.Models.Order", b =>
                {
                    b.Navigation("items");
                });
#pragma warning restore 612, 618
        }
    }
}
